# Generated by Django 6.0.3 on 2026-03-09 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visit',
            name='discount_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('waiting', 'Kutmoqda'), ('in_progress', 'Qabulda'), ('done', 'Tugatildi'), ('has_procedure', 'Protsedurasi bor')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='description',
            field=models.TextField(blank=True, help_text='Lavozim tavsifi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(choices=[('doctor', 'Doktor'), ('other', 'Boshqa xodim')], max_length=10),
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doktor'), ('receptionist', 'Resepsionist')], max_length=15)),
                ('worker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='clinic.worker')),
            ],
        ),
    ]
