# Generated by Django 6.0.3 on 2026-03-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_patient_gender_alter_service_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='clinic.worker'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'worker_type': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='clinic.worker'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='clinic.service'),
        ),
    ]
