# Generated by Django 6.0.3 on 2026-03-10 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_procedure_doctor_alter_visit_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ScheduledVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('activated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'worker_type': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_visits', to='clinic.worker')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_visits', to='clinic.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_from', to='clinic.visit')),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.service')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_services', to='clinic.visit')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='clinic.visit')),
            ],
            options={
                'ordering': ['date', 'number'],
                'unique_together': {('date', 'number')},
            },
        ),
    ]
