# Generated by Django 6.0.3 on 2026-03-10 01:54

from django.db import migrations


def migrate_services_forward(apps, schema_editor):
    """Copy existing Visit.service FK data to VisitService M2M."""
    Visit = apps.get_model('clinic', 'Visit')
    VisitService = apps.get_model('clinic', 'VisitService')
    for v in Visit.objects.filter(service__isnull=False):
        VisitService.objects.get_or_create(
            visit=v,
            service=v.service,
            defaults={'price_at_time': v.service.price}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_worker_room_number_scheduledvisit_visitservice_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_services_forward, migrations.RunPython.noop),
    ]
