# Generated by Django 6.0.3 on 2026-03-10 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_migrate_visit_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_per_session', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='procedure',
            name='price_per_session',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procedure',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='assigned_doctors', to='clinic.service'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='clinical_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_instances', to='clinic.clinicalprocedure'),
        ),
    ]
