# Generated by Django 6.0.3 on 2026-03-10 05:18

from django.db import migrations


def forward(apps, schema_editor):
    """Copy Worker.service FK to Worker.services M2M for all workers."""
    Worker = apps.get_model('clinic', 'Worker')
    for w in Worker.objects.filter(service__isnull=False):
        w.services.add(w.service)


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_clinicalprocedure_procedure_price_per_session_and_more'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
