# Generated by Django 6.0.3 on 2026-03-10 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_migrate_worker_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('expense_type', models.CharField(choices=[('recurring', 'Har oylik'), ('one_time', 'Bir martalik')], max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='queuenumber',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='queuenumber',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_numbers', to='clinic.worker'),
        ),
        migrations.AddField(
            model_name='scheduledvisit',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='scheduled_visits', to='clinic.service'),
        ),
        migrations.AlterUniqueTogether(
            name='queuenumber',
            unique_together={('date', 'number', 'doctor')},
        ),
    ]
