# Generated by Django 6.0.3 on 2026-03-10 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_expense_alter_queuenumber_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='doctor_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='VisitAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_attachments', to='clinic.visit')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
