# Generated by Django 6.0.3 on 2026-03-15 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_visit_doctor_name_visitattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('clinic_name', models.CharField(blank=True, default='', max_length=200)),
                ('commission_percent', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'surname'],
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='clinic.referralpartner'),
        ),
    ]
