# Generated by Django 6.0.3 on 2026-03-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_referralpartner_visit_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpartner',
            name='commission_fixed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referralpartner',
            name='commission_type',
            field=models.CharField(choices=[('percent', 'Foiz'), ('fixed', 'Belgilangan summa')], default='percent', max_length=10),
        ),
    ]
