# Generated by Django 6.0.3 on 2026-03-26 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_referralpartner_commission_fixed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='Model')),
                ('cost_price', models.IntegerField(default=0, verbose_name='Tannarx')),
                ('sell_price', models.IntegerField(default=0, verbose_name='Sotish narxi')),
                ('lens_type', models.CharField(blank=True, max_length=200, verbose_name='Linza turi')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Brend')),
                ('quantity', models.IntegerField(default=0, verbose_name='Miqdori')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='allergiya',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='anamnesis_morbi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='anamnesis_vitae',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='koz_olmasi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='koz_oynak_kontakt_linza',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='koz_soqqasi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='old_kamera',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='operatsiyalar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='qovoqlar_koz_yosh_yollari',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='rangdor_parda_qorachiq',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='shikoyatlar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='shox_parda',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='sklera',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='tashxis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='tavsiya',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='tomizilgan',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='EyeIOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_value', models.CharField(blank=True, max_length=20, verbose_name="OD (o'ng)")),
                ('os_value', models.CharField(blank=True, max_length=20, verbose_name='OS (chap)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iops', to='clinic.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iops', to='clinic.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EyeKRT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_d', models.CharField(blank=True, max_length=20, verbose_name='OD D')),
                ('od_mm', models.CharField(blank=True, max_length=20, verbose_name='OD MM')),
                ('od_a', models.CharField(blank=True, max_length=20, verbose_name='OD A')),
                ('os_d', models.CharField(blank=True, max_length=20, verbose_name='OS D')),
                ('os_mm', models.CharField(blank=True, max_length=20, verbose_name='OS MM')),
                ('os_a', models.CharField(blank=True, max_length=20, verbose_name='OS A')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krts', to='clinic.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krts', to='clinic.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EyeRefraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_s', models.CharField(blank=True, max_length=20, verbose_name='OD S')),
                ('od_c', models.CharField(blank=True, max_length=20, verbose_name='OD C')),
                ('od_a', models.CharField(blank=True, max_length=20, verbose_name='OD A')),
                ('os_s', models.CharField(blank=True, max_length=20, verbose_name='OS S')),
                ('os_c', models.CharField(blank=True, max_length=20, verbose_name='OS C')),
                ('os_a', models.CharField(blank=True, max_length=20, verbose_name='OS A')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refractions', to='clinic.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refractions', to='clinic.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlassSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('sell_price', models.IntegerField(default=0)),
                ('cost_price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('glasses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='clinic.glasses')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Kutmoqda'), ('in_progress', 'Jarayonda'), ('done', 'Tayyor')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_visits', to='clinic.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabVisitService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.IntegerField(default=0)),
                ('service_name', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_services', to='clinic.labvisit')),
            ],
            options={
                'ordering': ['service_number'],
            },
        ),
    ]
