# Generated by Django 6.0.3 on 2026-03-28 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_glasses_visit_allergiya_visit_anamnesis_morbi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doktor'), ('receptionist', 'Resepsionist'), ('seller', 'Sotuvchi')], max_length=15),
        ),
        migrations.CreateModel(
            name='LabQueueNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='clinic.labvisit')),
            ],
            options={
                'ordering': ['date', 'number'],
                'unique_together': {('date', 'number')},
            },
        ),
    ]
