# Generated by Django 6.0.3 on 2026-03-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_alter_useraccount_role_labqueuenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledvisit',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledvisit',
            name='lab_services_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
