# Generated by Django 6.0.3 on 2026-04-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_remove_visit_shikoyatlar_remove_visit_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glasssale',
            name='discount_amount',
            field=models.IntegerField(default=0, verbose_name="Chegirma (so'm)"),
        ),
    ]
