# Generated by Django 6.0.3 on 2026-04-24 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_glasssale_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='b_skan_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='b_skan_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='fundus_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='fundus_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='kp_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='kp_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='oct_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='oct_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='periferiya_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='periferiya_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='retsept_kontakt_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='retsept_kontakt_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='retsept_uzoq_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='retsept_uzoq_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='retsept_yaqin_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='retsept_yaqin_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='ubm_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='ubm_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dischargeform',
            name='protocol_number',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='eyeexamform',
            name='protocol_number',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='LasikForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tashxis', models.TextField(blank=True, default='')),
                ('operatsiya_turi', models.CharField(blank=True, default='', max_length=50)),
                ('ko_z', models.CharField(blank=True, default='', max_length=10)),
                ('octavius', models.BooleanField(default=False)),
                ('operatsiya_sanasi', models.DateField(blank=True, null=True)),
                ('oper_hirurg', models.CharField(blank=True, default='', max_length=200)),
                ('assistent', models.CharField(blank=True, default='', max_length=200)),
                ('vgd_od', models.CharField(blank=True, default='', max_length=20)),
                ('vgd_os', models.CharField(blank=True, default='', max_length=20)),
                ('preop_vis_od', models.CharField(blank=True, default='', max_length=20)),
                ('preop_sph_od', models.CharField(blank=True, default='', max_length=20)),
                ('preop_cyl_od', models.CharField(blank=True, default='', max_length=20)),
                ('preop_axis_od', models.CharField(blank=True, default='', max_length=20)),
                ('preop_vis_os', models.CharField(blank=True, default='', max_length=20)),
                ('preop_sph_os', models.CharField(blank=True, default='', max_length=20)),
                ('preop_cyl_os', models.CharField(blank=True, default='', max_length=20)),
                ('preop_axis_os', models.CharField(blank=True, default='', max_length=20)),
                ('postop_vis_od', models.CharField(blank=True, default='', max_length=20)),
                ('postop_vis_os', models.CharField(blank=True, default='', max_length=20)),
                ('holat', models.TextField(blank=True, default='Глаз спокоен, лоскут прилегает, среды прозрачные')),
                ('tavsiya', models.TextField(blank=True, default='1. наблюдение офтальмолога.\n2. ограничение физической нагрузки.')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.worker')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasik_forms', to='clinic.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostOpForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('davolash_boshlanishi', models.DateField(blank=True, null=True)),
                ('davolash_tugashi', models.DateField(blank=True, null=True)),
                ('asosiy_tashxis', models.TextField(blank=True, default='')),
                ('qoshimcha_tashxis', models.TextField(blank=True, default='')),
                ('hamroh_kasallik', models.TextField(blank=True, default='')),
                ('qabulda_vis_od', models.CharField(blank=True, default='', max_length=50)),
                ('qabulda_vis_os', models.CharField(blank=True, default='', max_length=50)),
                ('qabulda_od', models.CharField(blank=True, default='', max_length=200)),
                ('qabulda_os', models.CharField(blank=True, default='', max_length=200)),
                ('xususiyatlar', models.TextField(blank=True, default='')),
                ('operatsiya', models.TextField(blank=True, default='')),
                ('narkoz_turi', models.CharField(blank=True, default='', max_length=50)),
                ('operatsiya_sanasi', models.DateField(blank=True, null=True)),
                ('hirurg', models.CharField(blank=True, default='', max_length=200)),
                ('chiqimda_vis_od', models.CharField(blank=True, default='', max_length=50)),
                ('chiqimda_vis_os', models.CharField(blank=True, default='', max_length=50)),
                ('chiqimda_od', models.CharField(blank=True, default='', max_length=200)),
                ('chiqimda_os', models.CharField(blank=True, default='', max_length=200)),
                ('xususiyat_chiqim', models.TextField(blank=True, default='')),
                ('tavsiya', models.TextField(blank=True, default='Местный: антибиотик (10 дн.), НПВС (1 месяц), ГКС по схеме, кератопротектор.\nОбщий: антибиотик/витамины по показаниям.')),
                ('keyingi_qayta_korish', models.CharField(blank=True, default='', max_length=100)),
                ('lech_vrach', models.CharField(blank=True, default='', max_length=200)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.worker')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postop_forms', to='clinic.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrabismusForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shikoyat', models.TextField(blank=True, default='')),
                ('vis', models.CharField(blank=True, default='', max_length=100)),
                ('dev_darajasi', models.CharField(blank=True, default='', max_length=50)),
                ('tashxis', models.TextField(blank=True, default='')),
                ('recession_muscle', models.CharField(blank=True, default='', max_length=100)),
                ('recession_eye', models.CharField(blank=True, default='', max_length=10)),
                ('recession_mm', models.CharField(blank=True, default='', max_length=20)),
                ('resection_muscle', models.CharField(blank=True, default='', max_length=100)),
                ('resection_eye', models.CharField(blank=True, default='', max_length=10)),
                ('resection_mm', models.CharField(blank=True, default='', max_length=20)),
                ('transposition_eye', models.CharField(blank=True, default='', max_length=10)),
                ('postop_dev', models.CharField(blank=True, default='', max_length=50)),
                ('tavsiya', models.TextField(blank=True, default='1. Флоксасоза томчиси 4 маҳал.\n2. Қайта кўрув 7 кундан сўнг.')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.worker')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strabismus_forms', to='clinic.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
