# Generated by Django 6.0.3 on 2026-06-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_visit_b_skan_od_visit_b_skan_os_visit_fundus_od_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postopform',
            name='bemor_eslatma',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='postopform',
            name='bemor_eslatma_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='strabismusform',
            name='dorilar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='strabismusform',
            name='dorilar_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='strabismusform',
            name='gilaylik_keyin',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='strabismusform',
            name='gilaylik_keyin_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lasikform',
            name='holat',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lasikform',
            name='tavsiya',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='postopform',
            name='tavsiya',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='strabismusform',
            name='tavsiya',
            field=models.TextField(blank=True, default=''),
        ),
    ]
