# Generated by Django 6.0.3 on 2026-06-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_postopform_bemor_eslatma_postopform_bemor_eslatma_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasikform',
            name='preop_corr_od',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lasikform',
            name='preop_corr_os',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='gavhar_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='gavhar_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='korish_otkirligi_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='korish_otkirligi_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='korreksiya_bilan_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='korreksiya_bilan_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='koz_olmasi_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='koz_olmasi_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='koz_soqqasi_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='koz_soqqasi_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='oftalmoskopiya_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='oftalmoskopiya_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='old_kamera_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='old_kamera_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='qovoqlar_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='qovoqlar_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='rangdor_parda_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='rangdor_parda_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='shishasimon_tana_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='shishasimon_tana_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='shox_parda_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='shox_parda_os',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='sklera_od',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='sklera_os',
            field=models.TextField(blank=True, default=''),
        ),
    ]
