# Generated by Django 6.0.3 on 2026-06-22 11:47

from django.db import migrations, models


def seed_lab_services(apps, schema_editor):
    from clinic.lab_services import LAB_SERVICES
    LabServiceTemplate = apps.get_model('clinic', 'LabServiceTemplate')
    for row in LAB_SERVICES:
        num, name, price = row[0], row[1], row[2]
        ref = row[3] if len(row) > 3 else ''
        LabServiceTemplate.objects.get_or_create(
            number=num,
            defaults={'name': name, 'price': price, 'reference_value': ref},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_lasikform_preop_corr_od_lasikform_preop_corr_os_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabServiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('reference_value', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.RunPython(seed_lab_services, migrations.RunPython.noop),
    ]
