# Generated by Django 6.0.3 on 2026-06-22 19:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_labservicetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
