# Generated by Django 6.0.3 on 2026-06-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0021_visit_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitattachment',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
