# Generated by Django 6.0.3 on 2026-06-23 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0022_visitattachment_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptikaPatientPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retsept_uzoq_od', models.CharField(blank=True, default='', max_length=200)),
                ('retsept_uzoq_os', models.CharField(blank=True, default='', max_length=200)),
                ('retsept_yaqin_od', models.CharField(blank=True, default='', max_length=200)),
                ('retsept_yaqin_os', models.CharField(blank=True, default='', max_length=200)),
                ('retsept_kontakt_od', models.CharField(blank=True, default='', max_length=200)),
                ('retsept_kontakt_os', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='optika_prescription', to='clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='OptikaSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list)),
                ('total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optika_sales', to='clinic.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
